### PR TITLE
Airfoil-interp PR: Update r-test for new baseline

### PR DESCRIPTION
**Pull request by andrew-platt**
Also removed precompilier directive `SPLINE_INTERP` from AirfoilInfo now that we are satisfied with r-test baseline results using linear interp of airfoils in AD15.

### CODE REVIEW

**Comment by andrew-platt** [comment]
Don't merge yet!  I put this PR in before realizing one more baseline from Eagle still needs to be updated.  Should be in the next day or so...

**Comment by bjonkman** [comment]
@andrew-platt, @rafmudaf: Have you run all the baselines, yet? I haven't seen any more updates in r-test.

**Comment by rafmudaf** [comment]
Still working on it. I've been having a ton of trouble compiling OpenFAST on Eagle with my scripts, though I've made progress today. I'll update again in a few hours.

**Comment by andrew-platt** [comment]
Finally ready!  @rafmudaf had to manually rerun and update the r-test results on Eagle.

**Pull request merged**
